name: Publish release

on:
  release:
    types: published

env:
  ANDROID_SDK_TOOLS:  "6514223"
  ANDROID_NDK:        "22.0.7026061"
  ANDROID_CMAKE:      "3.10.2.4988404"

jobs:
  bintray:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - run: .github/installAndroidTools.sh

      - name: Download assets from this Release
        uses: ViliusSutkus89/release-asset-downloader@v1.0
        with:
          outputDirectory: 'releaseAssets'

      - name: Put release assets where gradle would have kept it after the build
        run: |
          ls -lha ./releaseAssets
          mkdir --parents ./ExecutableRunner/build/outputs/aar
          mv ./releaseAssets/ExecutableRunner-release.aar ./ExecutableRunner/build/outputs/aar/

          mkdir --parents ./ExecutableRunner/build/libs
          mv ./releaseAssets/ExecutableRunner-*-javadoc.jar ./ExecutableRunner/build/libs/
          mv ./releaseAssets/ExecutableRunner-android-*-sources.jar ./ExecutableRunner/build/libs/

      - name: Upload to Bintray
        run: ./gradlew bintrayUpload -PbintrayUser=${{ secrets.BINTRAY_API_USER }} -PbintrayApiKey=${{ secrets.BINTRAY_API_KEY }}

  versionIncrementer:
    runs-on: ubuntu-20.04
    needs: bintray
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - run: ./doincrementversion

      - uses: ViliusSutkus89/git-auto-commit-action@v4
        with:
          commit_message: "Post release version increment"
          file_pattern: ExecutableRunner/build.gradle
